export interface Property {
  id: number
  title: string
  location: string
  area: string
  bedrooms: number
  bathrooms: number
  garage: number // Added garage
  price: number // Added price
  image: string
}

export const mockProperties: Property[] = [
  {
    id: 1,
    title: "Apartamento de Luxo com Vista Panorâmica",
    location: "Copacabana, Rio de Janeiro",
    area: "1.800 m²",
    bedrooms: 3,
    bathrooms: 4,
    garage: 2,
    price: 1200000,
    image: "/images/hero.png",
  },
  {
    id: 2,
    title: "Estúdio Moderno no Coração da Cidade",
    location: "Pinheiros, São Paulo",
    area: "600 m²",
    bedrooms: 2,
    bathrooms: 3,
    garage: 1,
    price: 750000,
    image: "/images/hero.png",
  },
  {
    id: 3,
    title: "Casa Espaçosa com Jardim Privativo",
    location: "Jurerê Internacional, Florianópolis",
    area: "2.500 m²",
    bedrooms: 4,
    bathrooms: 5,
    garage: 3,
    price: 2500000,
    image: "/images/hero.png",
  },
  {
    id: 4,
    title: "Loft Urbano com Design Contemporâneo",
    location: "Centro, Salvador",
    area: "950 m²",
    bedrooms: 2,
    bathrooms: 2,
    garage: 1,
    price: 600000,
    image: "/images/hero.png",
  },
  {
    id: 5,
    title: "Residência Exclusiva em Condomínio Fechado",
    location: "Alphaville, São Paulo",
    area: "1.600 m²",
    bedrooms: 3,
    bathrooms: 3,
    garage: 2,
    price: 1800000,
    image: "/images/hero.png",
  },
  {
    id: 6,
    title: "Apartamento Clássico com Charme Histórico",
    location: "Santa Teresa, Rio de Janeiro",
    area: "1.200 m²",
    bedrooms: 3,
    bathrooms: 2,
    garage: 1,
    price: 900000,
    image: "/images/hero.png",
  },
  {
    id: 7,
    title: "Cobertura Duplex com Vista Deslumbrante",
    location: "Leblon, Rio de Janeiro",
    area: "3.000 m²",
    bedrooms: 5,
    bathrooms: 6,
    garage: 3,
    price: 3500000,
    image: "/images/hero.png",
  },
  {
    id: 8,
    title: "Studio Compacto e Funcional",
    location: "Moema, São Paulo",
    area: "550 m²",
    bedrooms: 1,
    bathrooms: 1,
    garage: 0,
    price: 400000,
    image: "/images/hero.png",
  },
  {
    id: 9,
    title: "Casa de Campo com Piscina",
    location: "Gramado, Rio Grande do Sul",
    area: "3.500 m²",
    bedrooms: 4,
    bathrooms: 4,
    garage: 2,
    price: 1500000,
    image: "/images/hero.png",
  },
  {
    id: 10,
    title: "Apartamento com Varanda Gourmet",
    location: "Barra da Tijuca, Rio de Janeiro",
    area: "1.000 m²",
    bedrooms: 2,
    bathrooms: 2,
    garage: 1,
    price: 850000,
    image: "/images/hero.png",
  },
]

export const mockLocations = [
  "Guarulhos, São Paulo",
  "São Paulo, São Paulo",
  "Campinas, São Paulo",
  "Rio de Janeiro, Rio de Janeiro",
  "Belo Horizonte, Minas Gerais",
  "Curitiba, Paraná",
  "Porto Alegre, Rio Grande do Sul",
  "Salvador, Bahia",
  "Fortaleza, Ceará",
  "Brasília, Distrito Federal",
  "Recife, Pernambuco",
  "Manaus, Amazonas",
  "Goiânia, Goiás",
  "Belém, Pará",
  "Joaçaba, Santa Catarina",
  "Gramado, Rio Grande do Sul",
  "Barra da Tijuca, Rio de Janeiro",
  "Copacabana, Rio de Janeiro",
  "Pinheiros, São Paulo",
  "Jurerê Internacional, Florianópolis",
  "Centro, Salvador",
  "Alphaville, São Paulo",
  "Santa Teresa, Rio de Janeiro",
  "Leblon, Rio de Janeiro",
  "Moema, São Paulo",
]
